/**
 * Copy the Monaco editor into /public so it is served from this origin.
 *
 * `@monaco-editor/react` has no bundled copy of the editor: unless it is told
 * otherwise it fetches the loader and the editor core from cdn.jsdelivr.net at
 * runtime. This prototype is required to work with the network unplugged, and
 * the coding workspace is the one screen where execution is the whole point, so
 * a CDN dependency there means the demo's best moment is also its most fragile.
 *
 * Copying rather than importing the package directly is deliberate: importing
 * pulls roughly 15MB of editor into the JavaScript bundle, which every page pays
 * for. As static files under /public it stays lazy, cached, and same-origin.
 *
 * The output is gitignored and regenerated by `prebuild`, so the repository does
 * not carry a vendored copy that can drift from the installed version.
 */

import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "node_modules/monaco-editor/min/vs");
const DEST = path.join(ROOT, "public/monaco/vs");

if (!fs.existsSync(SRC)) {
  console.error(`[monaco] ${SRC} not found. Is monaco-editor installed?`);
  process.exit(1);
}

// Skip the copy when it is already current, so a rebuild does not pay for it.
const stamp = path.join(ROOT, "public/monaco/.version");
const installed = JSON.parse(
  fs.readFileSync(path.join(ROOT, "node_modules/monaco-editor/package.json"), "utf8"),
).version;
if (fs.existsSync(stamp) && fs.readFileSync(stamp, "utf8").trim() === installed) {
  console.log(`[monaco] public/monaco/vs already at ${installed}`);
  process.exit(0);
}

fs.rmSync(path.join(ROOT, "public/monaco"), { recursive: true, force: true });
fs.mkdirSync(DEST, { recursive: true });
fs.cpSync(SRC, DEST, { recursive: true });
fs.writeFileSync(stamp, installed);

let bytes = 0;
const walk = (dir) => {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else bytes += fs.statSync(p).size;
  }
};
walk(DEST);
console.log(`[monaco] copied ${installed} to public/monaco/vs (${(bytes / 1024 / 1024).toFixed(1)}MB)`);
