#!/usr/bin/env node
/**
 * Download Satoshi from Fontshare and self-host it under /public/fonts.
 *
 * The app's typography is Satoshi, and pulling it from api.fontshare.com at
 * runtime is the difference between a demo that renders instantly on a hotel
 * network and one where a prospect watches the type reflow. It is also a hard
 * dependency on a third party being up during a sales call.
 *
 * Output is COMMITTED. Re-run only when the typeface or its weights change:
 *   npm run build:fonts
 *
 * Note: Fontshare serves Satoshi in 5 weights (300/400/500/700/900) even when
 * more are requested. 600 and 800 are synthesized by the browser, which is what
 * happened with the CDN too, so self-hosting loses nothing.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const OUT_DIR = join(ROOT, "public/fonts");
const CSS_URL =
  "https://api.fontshare.com/v2/css?f%5B%5D=satoshi@300,400,500,600,700,800,900&display=swap";
// Fontshare varies its response by user agent; a browser UA gets woff2.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

mkdirSync(OUT_DIR, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();
const blocks = css.split("@font-face").slice(1);

let out = "/* Satoshi, self-hosted. Generated by scripts/fetch-fonts.mjs - do not edit. */\n";
let count = 0;

for (const block of blocks) {
  // woff2 only. Every browser that can run this app supports it, so the woff and
  // ttf fallbacks are bytes nobody will ever download.
  const woff2 = block.match(/url\('(\/\/[^']+\.woff2)'\)/);
  const weight = block.match(/font-weight:\s*(\d+)/);
  const style = block.match(/font-style:\s*(\w+)/);
  if (!woff2 || !weight) continue;

  const italic = style && style[1] !== "normal";
  const file = `satoshi-${weight[1]}${italic ? `-${style[1]}` : ""}.woff2`;
  const response = await fetch(`https:${woff2[1]}`, { headers: { "User-Agent": UA } });
  if (!response.ok) {
    console.error(`[fonts] failed to download ${file}: HTTP ${response.status}`);
    process.exit(1);
  }
  writeFileSync(join(OUT_DIR, file), Buffer.from(await response.arrayBuffer()));
  count++;

  out +=
    `@font-face {\n  font-family: 'Satoshi';\n  src: url('/fonts/${file}') format('woff2');\n` +
    `  font-weight: ${weight[1]};\n  font-style: ${style ? style[1] : "normal"};\n  font-display: swap;\n}\n`;
}

if (count === 0) {
  console.error("[fonts] no @font-face blocks parsed - Fontshare may have changed its response format");
  process.exit(1);
}

writeFileSync(join(OUT_DIR, "satoshi.css"), out);
console.log(`[fonts] self-hosted ${count} weights -> public/fonts/`);
